all:
YodafyServidorIterativo.class: YodafyServidorIterativo.java
	javac YodafyServidorIterativo.java

YodafyClienteUDP.class: YodafyClienteUDP.java
	javac YodafyClienteUDP.java

servidor: YodafyServidorIterativo.class
	java YodafyServidorIterativo


cliente: YodafyClienteUDP.class
	java YodafyClienteUDP


clear:
	rm *~ *.class

